package:
  name: valpy
  version: 0.1.0

source:
  git_url: https://github.gatech.edu/mpatel636/valpy.git
  git_rev: main

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pip
    - setuptools
    - python
    - git
  run:
    - numpy
    - malavp::rudolfpy